#!/usr/bin/env node
/**
 * Seed Sanity CMS with all static tenant data.
 * Run: SANITY_WRITE_TOKEN=sk... node scripts/seed-sanity.mjs
 *
 * Excludes: sucremart + ramstack from Lindora comercios (tenants left).
 * Uses createOrReplace — safe to re-run.
 */

const PROJECT_ID = 'klr3qmou'
const DATASET = 'production'
const API_VERSION = '2024-01-01'
const TOKEN = process.env.SANITY_WRITE_TOKEN

if (!TOKEN) {
  console.error('❌  Set SANITY_WRITE_TOKEN env var first.')
  console.error('   Get it at: https://sanity.io/manage → project klr3qmou → API → Tokens')
  process.exit(1)
}

const MUTATIONS_URL = `https://${PROJECT_ID}.api.sanity.io/v${API_VERSION}/data/mutate/${DATASET}`

function doc(site, tenant) {
  return {
    _type: 'tenant',
    _id: `${site}-${tenant.slug}`,
    site,
    slug: { _type: 'slug', current: tenant.slug },
    name: tenant.name,
    section: tenant.section,
    category: tenant.category,
    tagline: tenant.tagline ?? '',
    description: tenant.description ?? '',
    featured: tenant.featured ?? false,
    ...(tenant.local    && { local:    tenant.local    }),
    ...(tenant.phone    && { phone:    tenant.phone    }),
    ...(tenant.whatsapp && { whatsapp: tenant.whatsapp }),
    ...(tenant.website  && { website:  tenant.website  }),
    ...(tenant.menuUrl  && { menuUrl:  tenant.menuUrl  }),
    ...(tenant.instagram && { instagram: tenant.instagram }),
    ...(tenant.facebook  && { facebook:  tenant.facebook  }),
    // Store logo/photo as logoUrl/photoUrl (designers can later replace with uploaded images)
    ...(tenant.logo  && { logoUrl:  tenant.logo  }),
    ...(tenant.photo && { photoUrl: tenant.photo }),
    hours: (tenant.hours ?? []).map((h, i) => ({
      _type: 'hoursRow',
      _key: `h${i}`,
      days: h.days,
      hours: h.hours,
    })),
  }
}

async function mutate(docs) {
  const mutations = docs.map(d => ({ createOrReplace: d }))
  // Send in batches of 100
  for (let i = 0; i < mutations.length; i += 100) {
    const batch = mutations.slice(i, i + 100)
    const res = await fetch(MUTATIONS_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${TOKEN}`,
      },
      body: JSON.stringify({ mutations: batch }),
    })
    const json = await res.json()
    if (!res.ok) {
      console.error('❌  Mutation failed:', JSON.stringify(json, null, 2))
      process.exit(1)
    }
    console.log(`  ✓ batch ${i / 100 + 1}: ${batch.length} docs`)
  }
}

// ─── DATA ────────────────────────────────────────────────────────────────────

const lindoraGastronomia = [
  { slug:'aji-limon', name:'Ají Limón', section:'gastronomia', category:'Gastronomía · Peruana', tagline:'Sabor Peruano', description:'Cocina peruana contemporánea con los sabores más auténticos de Perú. Ceviches, tiraditos y platos de fondo que transportan el alma de Lima a Lindora.', logo:'aji-limon.png', photo:'aji-limon.webp', hours:[{days:'Lunes a Domingo',hours:'12:00 md – 9:30 pm'}], phone:'2582-2279', local:'C27', instagram:'ajilimon_costarica', featured:true },
  { slug:'bbq-chicken', name:'BBQ Chicken', section:'gastronomia', category:'Gastronomía · Coreana', tagline:"Korea's Finest Fried Chicken", description:'El mejor pollo frito coreano de Costa Rica. Marinados auténticos, salsas únicas y una experiencia que mezcla la tradición coreana con el gusto local.', logo:'bbq-chicken.png', photo:'bbq-chicken.webp', hours:[{days:'Domingo a Jueves',hours:'12:00 md – 10:00 pm'},{days:'Viernes y Sábado',hours:'12:00 md – 11:00 pm'}], phone:'7227-6227', featured:false },
  { slug:'el-avila', name:'El Ávila Bar & Grill', section:'gastronomia', category:'Gastronomía · Venezolana', tagline:'Parrillada Venezolana', description:'La mejor parrillada venezolana de la zona. Cortes de primera, tequeños, arepas y todo el sabor de Venezuela servido con alma y calidez.', logo:'el-avila.png', photo:'el-avila.webp', hours:[{days:'Lunes a Jueves',hours:'11:30 am – 9:00 pm'},{days:'Viernes y Sábado',hours:'11:30 am – 10:00 pm'},{days:'Domingos',hours:'11:30 am – 5:00 pm'}], phone:'4702-2063', local:'L55', instagram:'elavilabargrill', featured:true },
  { slug:'kotoy', name:'Kotoy', section:'gastronomia', category:'Gastronomía · Japonesa & Fusión', tagline:'Japanese & Fusion', description:'Sushi, rolls de autor y fusión japonesa-latina en un ambiente vibrante. Kotoy redefine la experiencia japonesa en Costa Rica con creatividad y frescura.', logo:'kotoy.png', photo:'kotoy.webp', hours:[{days:'Lunes a Miércoles',hours:'12:00 md – 11:00 pm'},{days:'Jueves a Sábado',hours:'12:00 md – 11:30 pm'},{days:'Domingos',hours:'12:00 md – 10:00 pm'}], phone:'8531-0282', local:'L55', instagram:'kotoyjapanesecr', whatsapp:'50685310282', featured:true },
  { slug:'la-fabbrica', name:'La Fabbrica', section:'gastronomia', category:'Gastronomía · Italiana', tagline:'Pizzería – Tradición Italiana', description:'Pizzas artesanales al horno con ingredientes importados de Italia. Masas de larga fermentación, mozzarella fresca y el alma de una trattoria italiana auténtica.', logo:'la-fabbrica.png', photo:'la-fabbrica.webp', hours:[{days:'Lunes a Domingo',hours:'12:00 md – 10:30 pm'}], phone:'4055-1004', instagram:'lafabbricapizzeria', website:'https://lafabbricapizzeria.com', menuUrl:'https://lafabbricapizzeria.com/menu.html', featured:true },
  { slug:'naans-curries', name:'Naans & Curries', section:'gastronomia', category:'Gastronomía · India', tagline:'An Ethnic Indian Restaurant', description:'La auténtica cocina india de Costa Rica. Desde tikka masala hasta biryani, cada plato es preparado con especias traídas directamente de la India.', logo:'naans-curries.png', photo:'naans-curries.webp', hours:[{days:'Lunes a Domingo',hours:'11:00 am – 10:00 pm'}], phone:'2282-5470', local:'L55', instagram:'naanslindora', website:'https://www.naans-curries.com', menuUrl:'https://www.naans-curries.com/#menu', featured:false },
  { slug:'patisserie-amour', name:"Pâtisserie d'Amour", section:'gastronomia', category:'Gastronomía · Francesa', tagline:'Pastelería Francesa', description:'Croissants laminados a mano, éclairs, macarons y pasteles de temporada. Una pâtisserie francesa auténtica que perfuma las mañanas de Momentum.', logo:'patisserie-amour.png', photo:'patisserie-amour.webp', hours:[{days:'Lunes a Domingo',hours:'6:30 am – 6:00 pm'}], phone:'8583-0465', instagram:'patisseriedamour', website:'https://patisserie-damour-pasteleria-francesa-french-bakery.negocio.site/', featured:true },
  { slug:'porkys', name:"Porky's Burger Bar", section:'gastronomia', category:'Gastronomía · Americana', tagline:'Burger Bar', description:'Hamburguesas artesanales, costillas BBQ y los mejores anillos de cebolla de la zona. El sabor americano auténtico en el corazón de Lindora.', logo:'porkys.png', photo:'porkys.webp', hours:[{days:'Lunes a Domingo',hours:'11:30 am – 10:00 pm'}], phone:'2282-5057', instagram:'porkysburgerbarcostarica', website:'https://www.porkyscr.com', whatsapp:'50687838552', featured:false },
  { slug:'shawaddi', name:'Shawaddi', section:'gastronomia', category:'Gastronomía · Árabe', tagline:'Gastronomía Árabe', description:'Shawarmas, falafel y platos del Medio Oriente preparados con recetas tradicionales y los mejores ingredientes. El sabor de Oriente en Lindora.', logo:'shawaddi.png', photo:'shawaddi.webp', hours:[{days:'Lunes a Domingo',hours:'11:30 am – 9:30 pm'}], phone:'2282-5057', instagram:'shawaddishawarma', featured:false },
  { slug:'soda-tapia', name:'Soda Tapia', section:'gastronomia', category:'Gastronomía · Tica', tagline:'Cocina Tica', description:'El sabor de casa, hecho con amor. Casados, gallo pinto y todos los clásicos de la cocina tica preparados con la receta de siempre.', logo:'soda-tapia.png', photo:'soda-tapia.webp', hours:[{days:'Consultar horario',hours:''}], phone:'2222-6734', featured:false },
  { slug:'zocalo', name:'Zócalo', section:'gastronomia', category:'Gastronomía · Mexicana', tagline:'Auténtica Gastronomía Mexicana', description:'Tacos de comal, enchiladas, mezcales y cocteles mexicanos en un ambiente vibrante. Zócalo trae el corazón de México a Santa Ana.', logo:'zocalo.png', photo:'zocalo.webp', hours:[{days:'Lunes a Miércoles',hours:'12:00 md – 9:00 pm'},{days:'Jueves',hours:'12:00 md – 10:00 pm'},{days:'Viernes',hours:'12:00 md – 12:00 mn'},{days:'Sábado',hours:'11:30 am – 12:00 mn'},{days:'Domingo',hours:'11:30 am – 10:00 pm'}], phone:'8755-1448', instagram:'zocalocr', featured:true },
]

// NOTE: sucremart + ramstack intentionally excluded (tenants left Lindora)
const lindoraComercios = [
  { slug:'dongfeng', name:'Dongfeng', section:'comercios', category:'Comercios · Automotriz', tagline:'Agencia de Vehículos Nuevos', description:'Agencia oficial de vehículos Dongfeng en Costa Rica. Tecnología, diseño y eficiencia en un solo lugar dentro de Momentum Lindora.', logo:'dongfeng.png', photo:'dongfeng.webp', hours:[{days:'Lunes a Viernes',hours:'9:00 am – 6:00 pm'},{days:'Sábados',hours:'9:00 am – 5:00 pm'},{days:'Domingos',hours:'10:00 am – 4:00 pm'}], instagram:'dongfeng_costarica', website:'https://dongfengcr.com' },
  { slug:'george-bakkar', name:'George Bakkar', section:'comercios', category:'Comercios · Joyería', tagline:'Premium Handcrafted Jewelry', description:'Joyería artesanal de lujo diseñada y elaborada por George Bakkar. Piezas únicas que combinan maestría artesanal con diseño contemporáneo.', logo:'george-bakkar.png', photo:'george-bakkar.webp', hours:[{days:'Lunes a Sábados',hours:'10:30 am – 8:00 pm'},{days:'Domingos',hours:'11:00 am – 6:00 pm'}], phone:'2203-4704', instagram:'georgebakkar', whatsapp:'50688825469' },
  { slug:'lynk-co', name:'Lynk & Co', section:'comercios', category:'Comercios · Automotriz', tagline:'Agencia de Vehículos Nuevos', description:'Agencia oficial Lynk & Co en Costa Rica. Vehículos de diseño europeo con tecnología de última generación para el conductor moderno.', logo:'lynk-co.png', photo:'lynk-co.webp', hours:[{days:'Lunes a Viernes',hours:'9:00 am – 6:30 pm'},{days:'Sábados y Domingos',hours:'9:00 am – 2:00 pm'}], instagram:'lynk_cocr', website:'https://lynkco.cr' },
  { slug:'md-fajas', name:'M&D Fajas', section:'comercios', category:'Comercios · Moda & Bienestar', tagline:'Fajas · Moldeo · Control', description:'Especialistas en fajas de moldeo corporal y control. Soluciones de moda y bienestar diseñadas para realzar tu figura y mejorar tu calidad de vida.', logo:'md-fajas.png', photo:'md-fajas.webp', hours:[{days:'Lunes a Sábados',hours:'10:30 am – 8:00 pm'},{days:'Sábados y Domingos',hours:'11:00 am – 6:00 pm'}], instagram:'fajasmydoficialcostarica', website:'https://fajasmydcr.com', whatsapp:'50683763456' },
  { slug:'purple-express', name:'Purple Express', section:'comercios', category:'Comercios · Lifestyle', tagline:'High Quality Smoking Instruments', description:'Instrumentos de smoking de alta calidad y accesorios lifestyle. Una experiencia curada para el consumidor moderno que valora la calidad.', logo:'purple-express.png', photo:'purple-express.webp', hours:[{days:'Lunes a Sábados',hours:'10:00 am – 9:00 pm'},{days:'Domingos',hours:'10:00 am – 7:00 pm'}], instagram:'purple.express', website:'https://www.purpleexpressonline.com', whatsapp:'50686948888' },
  { slug:'runners', name:'Runners', section:'comercios', category:'Comercios · Deportivo', tagline:'El Mundo de los Corredores', description:'Todo lo que necesita un corredor en un solo lugar. Calzado técnico, ropa de performance y equipamiento para llevar tu entrenamiento al siguiente nivel.', logo:'runners.png', photo:'runners.webp', hours:[{days:'Lunes a Viernes',hours:'10:00 am – 7:00 pm'},{days:'Sábados',hours:'8:00 am – 5:00 pm'},{days:'Domingos',hours:'10:00 am – 5:00 pm'}], instagram:'runnerscostarica', website:'https://runnerscr.com', whatsapp:'50684518451' },
  { slug:'vinum', name:'Vinum Store', section:'comercios', category:'Comercios · Vinos & Licores', tagline:'Los mejores vinos nacionales e internacionales', description:'Una selección cuidadosamente curada de vinos nacionales e internacionales. La enología al alcance de los amantes del buen vivir en Lindora.', logo:'vinum.png', photo:'vinum.webp', hours:[{days:'Lunes a Miércoles',hours:'11:00 am – 8:00 pm'},{days:'Jueves a Sábado',hours:'9:00 am – 2:00 pm'},{days:'Domingos',hours:'11:00 am – 6:00 pm'}], phone:'2437-7300', instagram:'vinumcr', website:'https://vinumcr.com', local:'L55' },
]

const lindoraServicios = [
  { slug:'banco-lafise-lindora', name:'Banco LAFISE', section:'servicios', category:'Servicios · Bancario', tagline:'Servicios Bancarios y Financieros para Todos', description:'Sucursal del Banco LAFISE en Momentum Lindora. Servicios bancarios y financieros completos para personas y empresas con atención personalizada.', logo:'banco-lafise.png', photo:'banco-lafise-lindora.webp', hours:[{days:'Lunes a Viernes',hours:'9:00 am – 5:00 pm'},{days:'Sábados',hours:'9:00 am – 12:00 md'}], phone:'2246-2422', instagram:'bancolafisecr', local:'Local 2', featured:false },
  { slug:'go-moving', name:'Go Moving', section:'servicios', category:'Servicios · Fitness & Bienestar', tagline:'Acondicionamiento Físico Personalizado', description:'Centro especializado en transformar vidas a través del movimiento y el acondicionamiento físico personalizado. Rehabilitación muscular, programas de salud, rendimiento deportivo e inmersiones en frío.', logo:'go-moving.png', photo:'go-moving.webp', hours:[{days:'Lunes a Viernes',hours:'6:00 am – 8:00 pm'}], instagram:'gomovingcp', website:'https://www.gomovingcr.com', featured:false },
  { slug:'morphosis', name:'Morphosis', section:'servicios', category:'Servicios · Belleza & Cuidado Personal', tagline:'Belleza y Cuidado Personal', description:'Salón de belleza y cuidado personal de alta calidad en Momentum Lindora. Cortes, color, tratamientos capilares y servicios de estética con profesionales especializados.', logo:'morphosis.png', photo:'morphosis.webp', hours:[{days:'Lunes a Sábados',hours:'9:00 am – 7:00 pm'}], phone:'2282-6732', instagram:'salonmorphosis', local:'C13', featured:false },
  { slug:'national-car-rental', name:'National Enterprise Rent-A-Car', section:'servicios', category:'Servicios · Alquiler de Vehículos', tagline:'Enterprise Rent-A-Car', description:'Alquiler de vehículos National/Enterprise en Momentum Lindora. Amplia flota de vehículos para tus necesidades de movilidad con el respaldo de la cadena internacional.', logo:'national.png', photo:'national-car-rental.webp', hours:[{days:'Lunes a Jueves',hours:'8:00 am – 5:00 pm'},{days:'Sábados',hours:'8:00 am – 5:00 pm'}], phone:'2437-7300', local:'2A2', featured:false },
  { slug:'new-image', name:'New Image Medical & Surgery Center', section:'servicios', category:'Servicios · Centro Médico & Cirugía', tagline:'Medical & Surgery Center', description:'Centro médico y de cirugía especializado en procedimientos estéticos y médicos de alta calidad. Tecnología avanzada y un equipo de profesionales con experiencia internacional.', logo:'new-image.png', photo:'new-image.webp', hours:[{days:'Lunes a Sábados',hours:'9:00 am – 6:00 pm'}], phone:'7036-3241', instagram:'newimagecenter_', local:'2B', featured:false },
  { slug:'newgate-tattoos', name:'Newgate Tattoos', section:'servicios', category:'Servicios · Tatuajes & Arte Corporal', tagline:'Professional Tattooing Studio', description:'Estudio de tatuajes profesional en Momentum Lindora. Artistas especializados en diferentes estilos: realismo, blackwork, acuarela y diseños personalizados con los más altos estándares de higiene.', logo:'newgate-tattoos.png', photo:'newgate-tattoos.webp', hours:[{days:'Lunes a Sábado',hours:'10:00 am – 7:00 pm'},{days:'Domingo',hours:'Cerrado'}], phone:'7042-9319', instagram:'newgate.tattoo', featured:false },
  { slug:'rejuvenese', name:'Rejuvenese', section:'servicios', category:'Servicios · Cirugía Plástica & Estética', tagline:'Servicios de Cirugía Plástica y Estética', description:'Clínica especializada en cirugía plástica y procedimientos estéticos de alta gama. Resultados naturales y seguros para realzar tu confianza con el equipo de especialistas de Rejuvenese.', logo:'rejuvenese.png', photo:'rejuvenese.webp', hours:[{days:'Lunes a Viernes',hours:'9:00 am – 7:00 pm'},{days:'Sábados',hours:'8:00 am – 2:00 pm'}], phone:'2434-2087', instagram:'clinica_rejuvenese', local:'Local 30-31', featured:false },
  { slug:'estudio-sommos', name:'Estudio Sommos', section:'servicios', category:'Servicios · Fitness & Entrenamiento', tagline:'Estudio de Entrenamiento Personalizado', description:'Estudio de entrenamiento personalizado en la Mediplaza de Momentum Lindora. Clases cada hora de lunes a viernes con un enfoque integral en salud, rendimiento y bienestar.', logo:'estudio-sommos.png', photo:'estudio-sommos.webp', hours:[{days:'Lunes a Viernes',hours:'6:00 am – 9:00 pm'}], phone:'8593-5775', instagram:'estudiosommos', local:'Local 38 · Mediplaza', featured:false },
  { slug:'legatus', name:'Legatus Barbershop', section:'servicios', category:'Servicios · Barbería', tagline:'Calidad · Servicio', description:'Barbería de alta gama en Momentum Lindora. Cortes clásicos y contemporáneos, afeitados tradicionales y tratamientos capilares para el hombre moderno que exige lo mejor.', logo:'legatus.png', photo:'legatus.webp', hours:[{days:'Lunes a Sábado',hours:'9:00 am – 7:00 pm'}], instagram:'legatus.barbershop', featured:false },
  { slug:'nail-station', name:'Nail Station by Sense', section:'servicios', category:'Servicios · Nail Bar & Estética', tagline:'Nail Bar · Belleza & Cuidado', description:'Studio especializado en el cuidado y diseño de uñas. Manicuras, pedicuras, nail art y tratamientos de belleza en un ambiente premium y relajante dentro de Momentum Lindora.', logo:'nail-station.png', photo:'nail-station.webp', hours:[{days:'Lunes a Sábado',hours:'10:00 am – 7:00 pm'}], instagram:'nailstationbysense', featured:false },
]

const lindoraOfiplaza = [
  { slug:'desarrolladores506', name:'Desarrolladores 506', section:'ofiplaza', category:'Ofiplaza · Desarrollo Urbano', tagline:'Más de 49 años de experiencia', description:'Más de 49 años de experiencia en el área de desarrollo urbano y construcción en Costa Rica. Proyectos residenciales y comerciales con visión, calidad y compromiso.', logo:'desarrolladores506.png', photo:'desarrolladores506.webp', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 6:00 pm'}], phone:'2582-0505', local:'L58', instagram:'desarrolladores506', website:'http://www.desarrolladores506.com' },
  { slug:'macondo', name:'Macondo', section:'ofiplaza', category:'Ofiplaza · Administración de Condominios', tagline:'Mantenimiento & Administración', description:'Especialistas en el mantenimiento y administración profesional de condominios. Tranquilidad, orden y eficiencia para tu propiedad.', logo:'macondo.png', photo:'macondo.webp', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 5:00 pm'}], phone:'2282-2422', local:'L54', website:'http://www.macondocr.com' },
  { slug:'sales-xcelerator', name:'Sales Xcelerator', section:'ofiplaza', category:'Ofiplaza · Ventas & Consultoría', tagline:'El Poder Transformador de la Venta', description:'Formación, consultoría y estrategia de ventas para impulsar el crecimiento empresarial. En un mundo impulsado por la conexión, las ventas son la piedra angular del éxito.', logo:'sales-xcelerator.png', photo:'sales-xcelerator.webp', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 6:00 pm'}], phone:'7215-8335', instagram:'salesxcelerator.io' },
]

const lindoraMediplaza = [
  { slug:'aquanest', name:'AquaNest', section:'mediplaza', category:'Mediplaza · Hidroestimulación', tagline:'Centro de Hidroestimulación Infantil', description:'Centro de hidroestimulación para el desarrollo y el bienestar de tu hijo. Sesiones especializadas en agua para bebés y niños en un entorno seguro y cálido.', logo:'aquanest.png', photo:'aquanest.webp', hours:[{days:'Lunes a Viernes',hours:'9:00 am – 7:00 pm'},{days:'Sábados',hours:'9:00 am – 1:00 pm'}], phone:'6012-3507', website:'https://pediatricstudio.com', whatsapp:'50660123507' },
  { slug:'cosmetic-dental', name:'Cosmetic Dental Care', section:'mediplaza', category:'Mediplaza · Odontología', tagline:'Todas las Especialidades Dentales', description:'Centro dental con todas las especialidades. Implantes, ortodoncia, estética y endodoncia con tecnología de vanguardia y un equipo altamente especializado.', logo:'cosmetic-dental.png', photo:'cosmetic-dental.webp', hours:[{days:'Lunes y Jueves',hours:'9:30 am – 5:30 pm'},{days:'Martes, Miércoles y Viernes',hours:'9:00 am – 7:00 pm'}], phone:'2582-2100', local:'L32', instagram:'cosmetic_dental_care', website:'http://www.cosmetic-dentalcare.com' },
  { slug:'core-medical', name:'Core Medical Center', section:'mediplaza', category:'Mediplaza · Cirugía', tagline:'Clínica especialista en hernias y piso pélvico', description:'Clínica especializada en hernias y piso pélvico. Abordaje mínimamente invasivo y atención integral para devolverle calidad de vida a nuestros pacientes.', logo:'core-medical.png', photo:'core-medical.webp', hours:[{days:'Lunes a Viernes',hours:'9:00 am – 6:00 pm'}], phone:'6079-5000', instagram:'core.medicalcenter', website:'https://www.coremedicalcentercr.com' },
  { slug:'mdt-costa-rica', name:'MDT Costa Rica', section:'mediplaza', category:'Mediplaza · Fisioterapia', tagline:'Mechanical Diagnosis and Therapy', description:'Fisioterapia especializada con el método MDT (Mechanical Diagnosis and Therapy). Rehabilitación musculoesquelética de alta precisión para la recuperación y el rendimiento.', logo:'mdt-costa-rica.png', photo:'mdt-costa-rica.webp', hours:[{days:'Lunes a Viernes',hours:'9:00 am – 7:00 pm'},{days:'Sábados',hours:'8:00 am – 1:00 pm'}], phone:'2203-3305', local:'39', instagram:'fisioadriancampos', website:'http://fisioadriancampos.com' },
  { slug:'ortodoncia-loranca', name:'Ortodoncia Loranca Silva', section:'mediplaza', category:'Mediplaza · Ortodoncia', tagline:'Invisalign & Smartee', description:'Especialistas en ortodoncia invisible. Invisalign y Smartee para transformar tu sonrisa con la máxima discreción y los mejores resultados.', logo:'ortodoncia-loranca.png', photo:'ortodoncia-loranca.webp', hours:[{days:'Lunes a Jueves',hours:'10:00 am – 6:00 pm'},{days:'Sábados',hours:'8:00 am – 1:00 pm'}], phone:'6402-0012', instagram:'ortodoncialorancasilva' },
  { slug:'pediatric-studio', name:'Pediatric Studio', section:'mediplaza', category:'Mediplaza · Pediatría', tagline:'Centro de Atención Pediátrico Especializado', description:'Atención pediátrica especializada en un entorno diseñado para el bienestar de los más pequeños. Salud infantil con calidez, profesionalismo y confianza.', logo:'pediatric-studio.png', photo:'pediatric-studio.webp', hours:[{days:'Lunes a Viernes',hours:'9:00 am – 7:00 pm'},{days:'Sábados',hours:'9:00 am – 1:00 pm'}], phone:'6012-3507', instagram:'pediatricstudio', website:'https://pediatricstudio.com', whatsapp:'50660123507' },
  { slug:'plantimec', name:'Plantimec', section:'mediplaza', category:'Mediplaza · Podología', tagline:'Plantillas 100% Personalizadas', description:'Plantillas biomecánicas completamente personalizadas para el confort, la postura y el rendimiento físico. Soluciones podológicas con tecnología de precisión.', logo:'plantimec.png', photo:'plantimec.webp', hours:[{days:'Lunes a Viernes',hours:'9:00 am – 7:00 pm'},{days:'Sábados',hours:'8:00 am – 1:00 pm'}], phone:'2203-3305', local:'L39', instagram:'plantimec_cr', website:'http://www.plantimec.com', whatsapp:'50663245627' },
  { slug:'womens-care', name:"Women's Care", section:'mediplaza', category:'Mediplaza · Ginecología', tagline:'Atención Ginecológica y Obstétrica Integral', description:'Ginecología y obstetricia integral adaptada a tus necesidades. Un espacio de confianza y calidez para el cuidado de la mujer en todas sus etapas de vida.', logo:'womens-care.png', photo:'womens-care.webp', hours:[{days:'Lunes a Viernes',hours:'9:00 am – 7:00 pm'},{days:'Sábados',hours:'9:00 am – 1:00 pm'}], phone:'6012-3507', website:'https://pediatricstudio.com', whatsapp:'50660123507' },
]

const escazuGastronomia = [
  { slug:'entrecote', name:'Entrecote', section:'gastronomia', category:'Gastronomía · Restaurante', tagline:'Restaurante de autor', description:'Restaurante de autor en Momentum Escazú. Cocina de mercado con ingredientes frescos y una carta que combina técnica y sabor en un ambiente sofisticado y acogedor.', logo:'entrecote.png', photo:'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Martes a Jueves',hours:'12:00 md – 10:30 pm'},{days:'Viernes y Sábados',hours:'12:00 md – 11:00 pm'},{days:'Domingos',hours:'12:00 md – 10:00 pm'}], phone:'4052-3101', instagram:'entrecotecr', whatsapp:'50671248795', featured:true },
  { slug:'paladixo', name:'Paladixo', section:'gastronomia', category:'Gastronomía · Restaurante', tagline:'Restaurante y café', description:'Restaurante y café en Momentum Escazú con un ambiente tranquilo y una carta variada para disfrutar desde el desayuno hasta la hora del almuerzo.', logo:'paladixo.png', photo:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Sábado',hours:'7:00 am – 7:00 pm'}], phone:'7205-5358', instagram:'paladixo', featured:false },
  { slug:'capri', name:'Capri Escazú', section:'gastronomia', category:'Gastronomía · Restaurante', tagline:'Sabores mediterráneos en Escazú', description:'Capri Escazú trae los sabores del Mediterráneo a Momentum. Una propuesta gastronómica elegante y acogedora, ideal para almuerzos de trabajo y cenas especiales.', logo:'capri.png', photo:'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'11:00 am – 10:00 pm'},{days:'Sábados',hours:'12:00 md – 10:30 pm'}], featured:false },
]

const escazuServicios = [
  { slug:'contrology-pilates', name:'Contrology Pilates Center', section:'servicios', category:'Servicios · Pilates & Fitness', tagline:'Gimnasio y Centro de Fitness', description:'Centro de pilates y fitness con una metodología basada en el método Contrology original de Joseph Pilates. Fortalece tu core, mejora tu postura y transforma tu cuerpo.', logo:'contrology-pilates.png', photo:'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'7:00 am – 8:00 pm'}], phone:'2228-1420', instagram:'contrologypilatescenter', local:'OF15', featured:true },
  { slug:'gyrotronic', name:'Gyrotonic Studio Escazú', section:'servicios', category:'Servicios · GYROTONIC® & GYROKINESIS®', tagline:'Bienestar físico-mental para amantes del movimiento', description:'Studio de GYROTONIC® y GYROKINESIS® dedicado al bienestar físico-mental. Ubicado en el edificio fitness, piso 3, contiguo a Teatralia en Momentum Escazú.', logo:'gyrotronic.png', photo:'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Jueves',hours:'7:00 am – 7:00 pm'},{days:'Viernes',hours:'7:00 am – 2:00 pm'},{days:'Sábado',hours:'10:00 am – 12:00 pm'},{days:'Domingo',hours:'Cerrado'}], instagram:'gyrotonic_escazu', local:'Edificio fitness, Piso 3', featured:false },
  { slug:'ambrosia-estetica', name:'Ambrosía Estética', section:'servicios', category:'Servicios · Estética & Spa', tagline:'Servicio 100% profesional y de alta calidad', description:'Estética con servicio 100% profesional y de alta calidad. Tratamientos faciales, corporales y capilares que te harán sentir y lucir en tu mejor versión.', logo:'ambrosia-estetica.png', photo:'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Sábados',hours:'10:00 am – 8:00 pm'},{days:'Domingos',hours:'10:00 am – 6:30 pm'}], phone:'4001-7550', instagram:'ambrosiaestetica', featured:false },
  { slug:'estetica-nadira', name:'Estética Nadira', section:'servicios', category:'Servicios · Estética Facial & Corporal', tagline:'Cuidado facial y tratamientos corporales', description:'Centro de estética dedicado al cuidado facial y tratamientos corporales de alta calidad. Un equipo profesional comprometido con tu bienestar y tu belleza.', logo:'estetica-nadira.png', photo:'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 7:00 pm'}], phone:'2101-7114', instagram:'esteticanadiracr', local:'CM26A', featured:false },
  { slug:'teatralia', name:'Teatralia', section:'servicios', category:'Servicios · Ballet & Artes Escénicas', tagline:'Escuela de Ballet y Artes Escénicas', description:'Escuela de ballet y artes escénicas en Momentum Escazú. Clases de ballet clásico, danza contemporánea y teatro para niños, jóvenes y adultos.', logo:'teatralia.png', photo:'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Sábado',hours:'9:00 am – 7:00 pm'}], phone:'2537-4133', instagram:'escuela.teatralia', featured:false },
  { slug:'el-tramito-a-granel', name:'El Tramito a Granel', section:'servicios', category:'Servicios · Productos a Granel', tagline:'Sabores y aromas infinitos y saludables', description:'Un espacio para degustar los sabores y aromas infinitos y saludables. Productos a granel, especias, semillas y todo para una vida más natural y consciente.', logo:'el-tramito-a-granel.png', photo:'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Sábado',hours:'9:00 am – 6:00 pm'},{days:'Domingos',hours:'10:00 am – 4:00 pm'}], phone:'6074-5617', instagram:'eltramitoagranel', featured:false },
  { slug:'el-tallercito', name:'El Tallercito', section:'servicios', category:'Servicios · Arte & Educación', tagline:'Taller de arte para niños', description:'Taller de arte creativo para niños en Momentum Escazú. Clases de pintura, dibujo y manualidades en un ambiente divertido y estimulante para el desarrollo artístico infantil.', logo:'el-tallercito.png', photo:'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes y Martes',hours:'4:30 pm – 6:00 pm'},{days:'Miércoles',hours:'2:30 pm – 4:00 pm'}], phone:'8899-5757', instagram:'el_tallercito_de_arte_escazu', featured:false },
  { slug:'dj-arbitraje', name:'DJ Arbitraje', section:'servicios', category:'Servicios · Legal', tagline:'Arbitraje Internacional – Solución de Controversias', description:'Firma especializada en arbitraje internacional y resolución alternativa de controversias. Servicios legales de alta especialización para empresas y personas.', logo:'dj-arbitraje.png', photo:'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 5:00 pm'}], phone:'8303-6116', instagram:'dyalajimenezf', local:'OF2–OF3', featured:false },
]

const escazuOficentro = [
  { slug:'aliaxis', name:'Aliaxis', section:'oficentro', category:'Oficentro · Manufactura', tagline:'Hacemos que la vida fluya', description:'Aliaxis: dando forma a un futuro mejor conectando gente, agua y energía. Empresa líder global en sistemas de tuberías y fluidos con presencia regional en Momentum Escazú.', logo:'aliaxis.png', photo:'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 5:00 pm'}], phone:'2527-0500', instagram:'aliaxislatam', local:'OF11–OF12–OF13–OF14', featured:false },
  { slug:'proyectos-qr', name:'Proyectos QR', section:'oficentro', category:'Oficentro · Construcción', tagline:'Construcción – Remodelación – Estructuras Metálicas', description:'Empresa de construcción, remodelación y estructuras metálicas con amplia experiencia en Costa Rica. Proyectos de calidad con materiales de primera y cumplimiento de plazos.', logo:'proyectos-qr.png', photo:'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 6:00 pm'}], phone:'2654-6060', local:'CM27', featured:false },
  { slug:'sagrario-padilla', name:'Lic. Sagrario Padilla', section:'oficentro', category:'Oficentro · Servicios Legales', tagline:'Abogada y Notaria Pública – Derecho Aéreo', description:'Abogada y notaria pública especialista en derecho aéreo. Asesoría legal de alta especialización para aerolíneas, operadores aéreos y pasajeros.', logo:'sagrario-padilla.png', photo:'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Con cita previa',hours:''}], phone:'8826-6193', local:'CM28', featured:false },
  { slug:'impegno', name:'Impegno Wedding Center', section:'oficentro', category:'Oficentro · Bodas & Eventos', tagline:'Wedding Center', description:'Centro especializado en la organización de bodas y eventos especiales. Diseño, logística y producción de eventos únicos con atención al detalle y pasión por los momentos que perduran.', logo:'impegno.png', photo:'https://images.unsplash.com/photo-1519741497674-4b64bc1da1bf?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'9:00 am – 6:00 pm'}], phone:'7026-0226', instagram:'impegnocr', local:'CM31', featured:false },
  { slug:'rla-power', name:'RLA Power', section:'oficentro', category:'Oficentro · Tecnología IT', tagline:'Servicios y Tecnologías de la Información', description:'Empresa de servicios y tecnologías de la información. Soluciones IT, infraestructura de redes y soporte tecnológico para empresas en Costa Rica y Centroamérica.', logo:'rla-power.png', photo:'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 5:30 pm'}], phone:'2290-8824', local:'OF07', featured:false },
  { slug:'legal-vision', name:'Legal Vision', section:'oficentro', category:'Oficentro · Servicios Legales', tagline:'Servicios Legales', description:'Bufete de abogados con servicios legales integrales para personas y empresas. Experiencia, confianza y resultados en cada proceso legal que enfrentan sus clientes.', logo:'legal-vision.png', photo:'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 6:00 pm'}], phone:'2220-0306', local:'OF08–OF09–OF10', featured:false },
  { slug:'excellence-consulting', name:'Excellence Consulting', section:'oficentro', category:'Oficentro · Consultoría Empresarial', tagline:'Asesores integrales para el crecimiento económico', description:'Asesores integrales para lograr el crecimiento económico de las empresas. Consultoría estratégica, financiera y operacional para negocios en Costa Rica.', logo:'excellence-consulting.png', photo:'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'9:00 am – 5:00 pm'}], local:'OF6', featured:false },
  { slug:'firmamento', name:'Firmamento', section:'oficentro', category:'Oficentro · Banca de Inversión', tagline:'Banca de Inversión – Asesoría Financiera – Bienes Raíces', description:'Firma de banca de inversión, asesoría financiera y bienes raíces en Costa Rica. Soluciones financieras sofisticadas para inversionistas y empresas con visión de futuro.', logo:'firmamento.png', photo:'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 5:00 pm'}], phone:'2100-6051', website:'http://firmamentocp.com', local:'Piso 4 · OF05', featured:false },
  { slug:'dj-arbitraje-oficentro', name:'DJ Arbitraje', section:'oficentro', category:'Oficentro · Arbitraje Internacional', tagline:'Arbitraje Internacional – Solución de Controversias', description:'Firma especializada en arbitraje internacional y resolución alternativa de disputas. Procesos ágiles, transparentes y con los más altos estándares de neutralidad e imparcialidad.', logo:'dj-arbitraje.png', photo:'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 5:00 pm'}], phone:'8303-6116', instagram:'dyalajimenezf', local:'OF2–OF3', featured:false },
]

const escazuCentroMedico = [
  { slug:'goodmed-escazu', name:'GoodMed', section:'centro-medico', category:'Centro Médico · Salud Integral', tagline:'Profesionales en la Salud', description:'Grupo de profesionales de la salud con laboratorio clínico y clínica dental integrados. Atención de calidad para toda la familia en Momentum Escazú.', logo:'goodmed.png', photo:'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Laboratorio L–V',hours:'7:00 am – 6:00 pm'},{days:'Laboratorio Sábado',hours:'7:00 am – 1:00 pm'},{days:'Dental L–V',hours:'8:00 am – 6:00 pm'},{days:'Dental Sábado',hours:'8:00 am – 12:00 md'}], phone:'4001-2222', instagram:'goodmedcr', whatsapp:'50661168888', featured:true },
  { slug:'centro-medico-momentum', name:'Centro Médico Momentum', section:'centro-medico', category:'Centro Médico · Atención Integral', tagline:'Atención médica integral en Momentum Escazú', description:'Centro médico integral dentro de Momentum Escazú con especialistas en diversas áreas de la salud. Atención de alta calidad en un entorno premium y accesible.', logo:'centro-medico-momentum.png', photo:'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'7:00 am – 6:00 pm'}], featured:true },
  { slug:'skin-care-physicians', name:'Skin Care Physicians', section:'centro-medico', category:'Centro Médico · Dermatología', tagline:'Skin Care Physicians of Costa Rica', description:'Centro dermatológico especializado en el cuidado de la piel. Dermatología clínica, estética y tratamientos avanzados para proteger y embellecer tu piel.', logo:'skin-care-physicians.png', photo:'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'9:00 am – 7:00 pm'}], phone:'2101-9574', local:'CM40', featured:true },
  { slug:'age-metrics-medical', name:'Age Metrics Medical', section:'centro-medico', category:'Centro Médico · Medicina Anti-aging', tagline:'Medicina anti-envejecimiento', description:'Centro médico especializado en medicina anti-aging y longevidad. Protocolos científicamente respaldados para optimizar tu salud y ralentizar el envejecimiento.', logo:'age-metrics-medical.png', photo:'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 5:00 pm'}], phone:'2289-2358', featured:false },
  { slug:'vitae', name:'Vitae', section:'centro-medico', category:'Centro Médico · Laboratorio Clínico', tagline:'Profesionales en la salud', description:'Laboratorio clínico con un equipo de profesionales comprometidos con la salud. Análisis de precisión, resultados confiables y atención personalizada para cada paciente.', logo:'vitae.png', photo:'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'7:00 am – 4:00 pm'},{days:'Sábados',hours:'8:00 am – 12:00 pm'}], phone:'4001-2222', local:'Local 1', featured:false },
  { slug:'insalud', name:'InSalud', section:'centro-medico', category:'Centro Médico · Salud Masculina', tagline:'Centro de salud masculina en medicina regenerativa', description:'Centro especializado en salud masculina y medicina regenerativa. Servicios de onda de choque para disfunción eréctil, prostatitis, incontinencia urinaria y urología.', logo:'insalud.png', photo:'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 5:00 pm'}], phone:'+506 7235-2114', instagram:'insalud.costarica', local:'Piso 3 · C26E', featured:false },
  { slug:'centro-oncologico', name:'Centro Integral de Oncología', section:'centro-medico', category:'Centro Médico · Oncología', tagline:'Atención oncológica integral', description:'Centro integral de atención oncológica con un equipo multidisciplinario dedicado a brindar el mejor cuidado a los pacientes con cáncer en cada etapa del tratamiento.', logo:'centro-oncologico.png', photo:'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 5:00 pm'}], phone:'4052-2410', local:'Locales 4–5–6', featured:false },
  { slug:'caira-reumatologia', name:'Caira Reumatología', section:'centro-medico', category:'Centro Médico · Reumatología', tagline:'Especialista en Reumatología', description:'Consulta de reumatología con el Dr. Alexis Méndez Rodríguez, especialista en el diagnóstico y tratamiento de enfermedades reumáticas e inflamatorias.', logo:'caira-reumatologia.png', photo:'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 5:00 pm'}], phone:'2100-5501', local:'CM40-B', featured:false },
  { slug:'farmacia-la-arboleda', name:'Farmacia La Arboleda', section:'centro-medico', category:'Centro Médico · Farmacia', tagline:'¡Todo y Más!', description:'Farmacia con todo y más para el cuidado de tu salud. Medicamentos, productos de bienestar, cosméticos y atención farmacéutica profesional en Momentum Escazú.', logo:'farmacia-la-arboleda.png', photo:'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Sábado',hours:'8:00 am – 8:00 pm'}], phone:'2289-4991', instagram:'laarboleda.cr', whatsapp:'50686074253', featured:false },
  { slug:'schmaus-dental', name:'Schmaus Dental Care', section:'centro-medico', category:'Centro Médico · Odontología', tagline:'Soluciones dentales óptimas de la más alta calidad', description:'Centro dental con dentistas especializados en encontrar soluciones dentales óptimas de la más alta calidad. Cuidado de tu sonrisa con tecnología y precisión.', logo:'schmaus-dental.png', photo:'https://images.unsplash.com/photo-1606811841689-23dfddce3e66?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'9:00 am – 6:00 pm'}], phone:'8791-6539', instagram:'schmaus_dental_center', featured:false },
  { slug:'la-clinique', name:'La Clinique', section:'centro-medico', category:'Centro Médico · Estética Médica', tagline:'Medicina estética de alto nivel', description:'Clínica de medicina estética y tratamientos de rejuvenecimiento facial y corporal. Un espacio sofisticado dedicado a realzar tu belleza con los más avanzados procedimientos.', logo:'la-clinique.png', photo:'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'9:00 am – 6:00 pm'}], featured:false },
  { slug:'kinesis', name:'Kinesis', section:'centro-medico', category:'Centro Médico · Kinética Dento Facial', tagline:'Kinética Dento Facial', description:'Especialistas en kinética dento facial, ortodoncia y tratamientos de estética dental. Tecnología de vanguardia con un enfoque funcional y estético del movimiento facial.', logo:'kinesis.png', photo:'https://images.unsplash.com/photo-1606811841689-23dfddce3e66?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 5:00 pm'}], featured:false },
  { slug:'audinsa', name:'Audinsa', section:'centro-medico', category:'Centro Médico · Clínica Auditiva', tagline:'Clínica Auditiva', description:'Clínica auditiva especializada en diagnóstico y rehabilitación del sistema auditivo. Equipos de última generación y profesionales comprometidos con tu calidad de vida.', logo:'audinsa.png', photo:'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 5:00 pm'}], featured:false },
  { slug:'wellness-institute', name:'Rosanna Mauro – Wellness Institute', section:'centro-medico', category:'Centro Médico · Nutrición & Coaching', tagline:'Nutrición Funcional · Coaching Integrativo · Mindfulness · Neurofeedback', description:'Instituto de bienestar integral con enfoque en nutrición funcional, coaching integrativo, mindfulness y neurofeedback. Herramientas científicas para transformar tu vida.', logo:'wellness-institute.png', photo:'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 7:00 pm'},{days:'Sábado',hours:'9:00 am – 1:00 pm'}], phone:'8557-8250', instagram:'rosannamauro_wellness', featured:false },
]

const pinaresGastronomia = [
  { slug:'bottega', name:'Bottega Privée', section:'gastronomia', category:'Gastronomía · Italiana', tagline:'Pasión por Italia', description:'Alta cocina italiana en un ambiente íntimo y sofisticado. Pastas frescas, risottos y una carta de vinos seleccionada con la misma pasión con que se prepara cada plato.', logo:'bottega.png', photo:'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Sábado',hours:'12:00 md – 10:00 pm'},{days:'Domingo',hours:'12:00 md – 9:00 pm'}], phone:'4001-5931', instagram:'bottegapriveecr', website:'https://bottegaprive.com', menuUrl:'https://qrcgcustomers.s3-eu-west-1.amazonaws.com/account9629358/8930577_1.pdf', featured:true },
  { slug:'boston-beer-garden', name:"Boston's Beer Garden", section:'gastronomia', category:'Gastronomía · Bar & Grill', tagline:'Beer Garden', description:'El mejor beer garden de Pinares. Cervezas artesanales, cocteles de autor y una carta de comida que acompaña perfectamente cada trago en un ambiente relajado y vibrante.', logo:'bostons.png', photo:'https://images.unsplash.com/photo-1567696911980-2eed69a46042?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Sábados',hours:'11:45 am – 10:45 pm'},{days:'Domingos',hours:'11:45 am – 9:00 pm'}], phone:'6097-4755', instagram:'bostonsbeergarden', whatsapp:'50660974755', featured:false },
  { slug:'chamo-gourmet', name:'CHAMO GOURMET', section:'gastronomia', category:'Gastronomía · Venezolana', tagline:'Restaurante Venezolano', description:'La auténtica sazón venezolana en Momentum Pinares. Pabellón criollo, tequeños, arepas y lo mejor de la gastronomía venezolana preparado con sabor de hogar.', logo:'chamo-gourmet.png', photo:'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes',hours:'12:00 md – 9:00 pm'},{days:'Martes a Jueves',hours:'12:00 md – 10:00 pm'},{days:'Viernes y Sábado',hours:'12:00 md – 11:00 pm'},{days:'Domingo',hours:'12:00 md – 9:00 pm'}], phone:'8496-6860', instagram:'chamogourmetcr', featured:false },
  { slug:'da-noi', name:'Gelateria Da Noi', section:'gastronomia', category:'Gastronomía · Italiana · Gelato', tagline:'El mejor gelato de Costa Rica', description:'El mejor gelato artesanal de Costa Rica. Preparado diariamente con ingredientes de primera calidad, Da Noi trae la tradición heladera italiana directamente a Pinares.', logo:'da-noi.png', photo:'https://images.unsplash.com/photo-1560008581-09826d1de69e?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Domingo',hours:'11:00 am – 9:00 pm'}], phone:'2272-6131', instagram:'danoi_cr', featured:true },
  { slug:'dennys', name:"Denny's Costa Rica", section:'gastronomia', category:'Gastronomía · Americana · Diner', tagline:'Tu Diner, Tu Lugar', description:"El diner americano de toda la vida, abierto las 24 horas los 365 días del año. Pancakes, omelettes, burgers y todo lo que hace grande a Denny's.", logo:'dennys.png', photo:'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Todos los días',hours:'Abierto 24 horas'}], phone:'2271-9090', instagram:'dennyscostarica', featured:false },
  { slug:'el-caminito', name:'Parrillada El Caminito', section:'gastronomia', category:'Gastronomía · Argentina & Uruguaya', tagline:'Parrillada Rioplatense', description:'Parrillada con influencia argentina y uruguaya. Cortes al punto, chorizos artesanales y ese sabor rioplatense que convierte cada visita en una celebración.', logo:'el-caminito.png', photo:'https://images.unsplash.com/photo-1432139509613-5c4255815697?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Domingo',hours:'11:00 am – 9:30 pm'},{days:'Lunes a Jueves',hours:'11:00 am – 11:00 pm'},{days:'Viernes y Sábado',hours:'11:00 am – 11:30 pm'}], phone:'2272-8505', instagram:'parrilladaelcaminito', featured:true },
  { slug:'espressivo-bistro', name:'Espressivo Bistró', section:'gastronomia', category:'Gastronomía · Bistró', tagline:'Buen comer, arte y espressión', description:'El bistró del Teatro Espressivo: buen comer, arte y espressión. Un espacio donde la gastronomía se fusiona con la cultura para crear una experiencia única.', logo:'espressivo-bistro.png', photo:'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Jueves',hours:'10:00 am – 8:00 pm'},{days:'Viernes',hours:'10:00 am – 11:00 pm'},{days:'Sábados',hours:'9:00 am – 11:00 pm'},{days:'Domingos',hours:'9:00 am – 9:00 pm'}], phone:'2267-1825', instagram:'espressivocr', featured:false },
  { slug:'fishermans', name:"Fisherman's Seafood", section:'gastronomia', category:'Gastronomía · Mariscos', tagline:'Restaurante de Mariscos – Seafood', description:'El mejor restaurante de mariscos en Pinares. Frescura del mar en cada plato: ceviche, camarones, langosta y todo el sabor del Pacífico costarricense.', logo:'fishermans.png', photo:'https://images.unsplash.com/photo-1544025162-d76538b5f90f?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Jueves',hours:'12:00 md – 10:00 pm'},{days:'Viernes y Sábado',hours:'12:00 md – 11:00 pm'},{days:'Domingo',hours:'12:00 md – 9:00 pm'}], phone:'7035-1475', instagram:'fishermans_seafoodcr', featured:false },
  { slug:'la-fonda-azteca', name:'La Fonda Azteca', section:'gastronomia', category:'Gastronomía · Mexicana', tagline:'Auténtica Comida Mexicana', description:'Auténtica cocina mexicana en el corazón de Pinares. Enchiladas, mole, tacos de comal y el sabor de México preparado con recetas tradicionales.', logo:'la-fonda-azteca.png', photo:'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Jueves',hours:'11:30 am – 10:00 pm'},{days:'Viernes y Sábados',hours:'11:30 am – 12:00 mn'},{days:'Domingos',hours:'11:30 am – 9:00 pm'}], phone:'6092-8524', instagram:'la_fonda_azteca', featured:false },
  { slug:'matsuri', name:'Matsuri', section:'gastronomia', category:'Gastronomía · Japonesa', tagline:'Cocina japonesa, sushi, teppanyaki y fusión', description:'La referencia de la cocina japonesa en Pinares. Sushi, sashimi, teppanyaki en vivo y fusión japonesa preparada con la más alta técnica y productos frescos.', logo:'matsuri.png', photo:'https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'11:00 am – 10:00 pm'},{days:'Sábado y Domingo',hours:'11:00 am – 10:30 pm'}], phone:'2271-4440', instagram:'matsuricr', featured:true },
  { slug:'mcdonalds', name:"McDonald's", section:'gastronomia', category:'Gastronomía · Comida Rápida', tagline:'¡Me Encanta!', description:"El restaurante más visitado del mundo, ahora en Momentum Pinares. Desayunos, burgers, McNuggets y todo lo que hace a McDonald's inconfundible.", logo:'mcdonalds.png', photo:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Domingo a Jueves',hours:'7:00 am – 12:00 mn'},{days:'Viernes y Sábado',hours:'7:00 am – 3:00 am'}], phone:'2271-4105', instagram:'mcdonaldscr', website:'https://www.mcdonalds.co.cr', menuUrl:'https://www.mcdonalds.co.cr/menu/mc-combo', featured:false },
  { slug:'naans-curries-pinares', name:'Naans & Curries', section:'gastronomia', category:'Gastronomía · India', tagline:'An Ethnic Indian Restaurant', description:'La auténtica cocina india en Pinares. Curries aromáticos, tandoori, biryanis y naans recién salidos del horno preparados con especias importadas directamente de India.', logo:'naans-curries.png', photo:'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Domingo',hours:'12:00 md – 11:00 pm'}], phone:'2271-7777', instagram:'naanscurriespinares', website:'http://www.naans-curries.com', menuUrl:'https://www.naans-curries.com/#menu', featured:false },
  { slug:'pikeos', name:'Pikeos', section:'gastronomia', category:'Gastronomía · Peruana & Fusión', tagline:'Restaurante Fusión Peruano', description:'Fusión peruana de autor con los mejores sabores de Lima adaptados a la cocina contemporánea. Ceviches, causas, tiraditos y una experiencia gastronómica de primer nivel.', logo:'pikeos.png', photo:'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Miércoles',hours:'11:30 am – 10:00 pm'},{days:'Jueves',hours:'11:30 am – 11:00 pm'},{days:'Viernes a Sábados',hours:'11:30 am – 12:00 mn'},{days:'Domingos',hours:'11:30 am – 9:00 pm'}], phone:'6170-3910', featured:false },
  { slug:'sazon-tico', name:'Sazón Tico', section:'gastronomia', category:'Gastronomía · Tica', tagline:'Cocina Tica', description:'El sabor auténtico de Costa Rica en Momentum Pinares. Desayunos ticos, casados, gallo pinto y todo el repertorio de la cocina nacional preparado con amor.', logo:'sazon-tico.png', photo:'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'11:00 am – 10:00 pm'},{days:'Sábados',hours:'8:00 am – 10:00 pm'},{days:'Domingos',hours:'8:00 am – 8:00 pm'}], phone:'8730-0280', instagram:'sazontico_pinares', featured:false },
  { slug:'subway', name:'Subway', section:'gastronomia', category:'Gastronomía · Sándwiches', tagline:'Come Fresco', description:'Sándwiches frescos personalizados con ingredientes de tu elección. Con servicio express para quienes buscan comer bien y rápido en Momentum Pinares.', logo:'subway.png', photo:'https://images.unsplash.com/photo-1481070414801-51fd723f6cf2?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Domingo',hours:'7:00 am – 10:00 pm'}], phone:'2271-4875', instagram:'subwaycr', featured:false },
  { slug:'tacobar', name:'Tacobar Killer Fish Tacos', section:'gastronomia', category:'Gastronomía · Mexicana', tagline:'Killer Fish Tacos', description:'Los mejores tacos de pescado en Momentum Pinares. Tortillas de maíz, ingredientes frescos y salsas artesanales en un ambiente relajado y vibrante.', logo:'tacobar.png', photo:'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Sábado',hours:'11:00 am – 10:00 pm'},{days:'Domingos',hours:'11:00 am – 9:00 pm'}], featured:false },
  { slug:'teatro-espressivo', name:'Teatro Espressivo', section:'gastronomia', category:'Gastronomía · Café & Bar', tagline:'Café de especialidad y coctelería', description:'Un espacio donde el café de especialidad se encuentra con la coctelería de autor. Teatro Espressivo fusiona arte, cultura y gastronomía en un ambiente único en Pinares.', logo:'teatro-espressivo.png', photo:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Jueves',hours:'7:00 am – 10:00 pm'},{days:'Viernes y Sábado',hours:'7:00 am – 11:00 pm'}], featured:false },
  { slug:'terraza-97', name:'Terraza 97', section:'gastronomia', category:'Gastronomía · Restaurante', tagline:'Restaurante con terraza', description:'Un restaurante con personalidad propia y una terraza que invita a quedarse. Cocina de autor, ambiente sofisticado y una carta que sorprende en cada visita.', logo:'terraza-97.png', photo:'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Jueves',hours:'12:00 md – 10:00 pm'},{days:'Viernes a Domingo',hours:'12:00 md – 11:00 pm'}], phone:'8437-9797', featured:false },
  { slug:'bbq-chicken-pinares', name:'BBQ Chicken', section:'gastronomia', category:'Gastronomía · Pollo & BBQ', tagline:'Pollo a las brasas y sabores BBQ', description:'Pollo al carbón y opciones BBQ preparadas con marinadas artesanales. Un clásico de los sabores ahumados en Momentum Pinares con opciones para comer en el local o llevar.', logo:'bbq-chicken.png', photo:'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Domingo',hours:'10:00 am – 10:00 pm'}], featured:false },
]

const pinaresComercios = [
  { slug:'aira-pilates', name:'Aira Pilates Studio', section:'comercios', category:'Comercios · Fitness & Wellness', tagline:'Pilates Reformer Studio', description:'Estudio de Pilates Reformer en Momentum Pinares. Clases personalizadas en grupos pequeños para mejorar tu fuerza, flexibilidad y bienestar general.', logo:'aira-pilates.png', photo:'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes (mañana)',hours:'6:00 am – 11:00 am'},{days:'Lunes a Viernes (tarde)',hours:'5:00 pm – 7:00 pm'},{days:'Sábado y Domingo',hours:'8:00 am – 1:00 pm'}], phone:'6120-1314', instagram:'aira_pilatescr', whatsapp:'50661201314' },
  { slug:'alfombra-roja', name:'Alfombra Roja', section:'comercios', category:'Comercios · Calzado', tagline:'Tienda de zapatos con 100% cuero', description:'Zapatería especializada en calzado 100% cuero. Diseños exclusivos, materiales de primera calidad y el confort que mereces en cada paso.', logo:'alfombra-roja.png', photo:'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Domingo',hours:'10:00 am – 7:00 pm'}], phone:'6044-4062', instagram:'alfombrarojatienda', whatsapp:'50660444062' },
  { slug:'antonella-boutique', name:'Antonella Boutique', section:'comercios', category:'Comercios · Moda', tagline:'Estilos exclusivos y ropa de calidad', description:'Boutique con estilos exclusivos y ropa de calidad a un excelente precio. Moda para la mujer moderna con un surtido que se renueva constantemente.', logo:'antonella-boutique.png', photo:'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Sábado',hours:'10:30 am – 7:00 pm'},{days:'Domingo',hours:'11:00 am – 5:30 pm'}], phone:'8399-5422', instagram:'antonellaboutiquecr', whatsapp:'50683995422' },
  { slug:'auto-pits', name:'AutoPits', section:'comercios', category:'Comercios · Automotriz', tagline:'Centro de Servicio Automotriz', description:'Centro de servicio automotriz de confianza en Momentum Pinares. Mantenimiento preventivo, cambio de aceite y revisión técnica para tu vehículo.', logo:'auto-pits.png', photo:'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'7:30 am – 6:00 pm'},{days:'Sábados',hours:'8:00 am – 5:00 pm'},{days:'Domingos',hours:'9:00 am – 1:00 pm'}], phone:'2522-7474', instagram:'autopitscostarica' },
  { slug:'ayana-fashion', name:'Ayana Fashion', section:'comercios', category:'Comercios · Moda', tagline:'Ropa y complementos', description:'Ropa y complementos de moda para la mujer contemporánea. Tendencias internacionales con precios accesibles y una atención personalizada que marca la diferencia.', logo:'ayana-fashion.png', photo:'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Jueves',hours:'10:30 am – 8:00 pm'},{days:'Viernes y Sábados',hours:'10:30 am – 9:00 pm'},{days:'Domingos',hours:'11:00 am – 7:00 pm'}], phone:'2272-3059', instagram:'ayana_fashion' },
  { slug:'banco-lafise', name:'Banco LAFISE', section:'comercios', category:'Comercios · Bancario', tagline:'Servicios Bancarios', description:'Sucursal del Banco LAFISE en Momentum Pinares. Servicios bancarios y financieros completos para personas y empresas con atención personalizada.', logo:'banco-lafise.png', photo:'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'9:00 am – 5:00 pm'},{days:'Sábado',hours:'9:00 am – 12:00 md'}], phone:'2246-2000', instagram:'bancolafisecr' },
  { slug:'canet', name:'Persianas Canet', section:'comercios', category:'Comercios · Decoración', tagline:'Decorando tu mundo interior', description:'Especialistas en persianas y decoración de interiores. Soluciones a medida para transformar tus espacios con estilo, funcionalidad y los mejores materiales.', logo:'canet.png', photo:'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'10:00 am – 6:00 pm'},{days:'Sábado',hours:'9:00 am – 5:00 pm'},{days:'Domingo',hours:'Cerrado'}], phone:'2272-7717', instagram:'persianas_canet' },
  { slug:'clean-clean', name:'Clean & Clean', section:'comercios', category:'Comercios · Tintorería', tagline:'Tintorería Rápida – Cuidamos tus prendas', description:'Tintorería de servicio rápido y de calidad. Cuidamos tus prendas más preciadas con los procesos más modernos y una atención que garantiza resultados impecables.', logo:'clean-clean.png', photo:'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Sábados',hours:'8:00 am – 8:00 pm'},{days:'Domingos',hours:'10:00 am – 6:00 pm'}], phone:'2272-7919' },
  { slug:'davivienda', name:'Davivienda', section:'comercios', category:'Comercios · Bancario', tagline:'Banco que enriquece la vida', description:'Sucursal de Davivienda en Momentum Pinares. Un banco comprometido con enriquecer la vida de sus clientes con integridad, innovación y excelencia en el servicio.', logo:'davivienda.png', photo:'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'9:00 am – 5:00 pm'},{days:'Sábado',hours:'9:00 am – 12:30 md'}], phone:'2287-1752' },
  { slug:'dkore', name:"D'kore Floristería", section:'comercios', category:'Comercios · Floristería', tagline:'Floristería para todo tipo de eventos', description:'Floristería especializada en bodas, baby shower, eventos corporativos, graduaciones y primeras comuniones. Arte floral con pasión para hacer tus momentos inolvidables.', logo:'dkore.png', photo:'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Sábado',hours:'10:00 am – 7:00 pm'},{days:'Domingo',hours:'10:00 am – 5:00 pm'}], phone:'2272-9900', instagram:'dkorefloristeria' },
  { slug:'el-armario', name:'El Armario', section:'comercios', category:'Comercios · Decoración & Hogar', tagline:'Decoración, regalos, telas y muebles', description:'Tienda de decoración con regalos, telas y muebles únicos. Un espacio curado para quienes buscan transformar sus hogares con piezas que reflejan personalidad y buen gusto.', logo:'el-armario.png', photo:'https://images.unsplash.com/photo-1534482421-64566f976cfa?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'10:30 am – 7:30 pm'}], phone:'8887-3904', instagram:'el_armario_cr' },
  { slug:'fun-in-a-box', name:'Fun In a Box', section:'comercios', category:'Comercios · Regalos', tagline:'Gifts and More', description:'La tienda de regalos y sorpresas de Momentum Pinares. Desde detalles creativos hasta experiencias únicas, Fun In a Box tiene el regalo perfecto para cada ocasión.', logo:'fun-in-a-box.png', photo:'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Domingo',hours:'10:00 am – 7:30 pm'}], phone:'7190-1739', instagram:'funinaboxcr' },
  { slug:'gnc', name:'GNC', section:'comercios', category:'Comercios · Suplementos & Nutrición', tagline:'Live Well', description:'La cadena líder mundial en suplementos nutricionales y productos de salud. Proteínas, vitaminas, quemadores y todo lo que necesitas para alcanzar tus metas.', logo:'gnc.png', photo:'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Sábado',hours:'8:00 am – 7:00 pm'},{days:'Domingo',hours:'9:00 am – 6:00 pm'}], phone:'2272-9530', instagram:'gnc.cr' },
  { slug:'goodmed', name:'GoodMed', section:'comercios', category:'Comercios · Centro Médico', tagline:'Profesionales en la Salud', description:'Grupo de profesionales de la salud con laboratorio clínico y clínica dental integrados. Atención de calidad para toda la familia en Momentum Pinares.', logo:'goodmed.png', photo:'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Laboratorio L–V',hours:'7:00 am – 4:30 pm'},{days:'Laboratorio Sábado',hours:'8:00 am – 1:00 pm'},{days:'Dental L–V',hours:'8:00 am – 6:00 pm'},{days:'Dental Sábado',hours:'8:00 am – 12:00 md'}], phone:'4001-2222', instagram:'goodmedcr', whatsapp:'50661168888' },
  { slug:'ishop', name:'iShop', section:'comercios', category:'Comercios · Tecnología Apple', tagline:'Distribuidor Autorizado Apple en Costa Rica', description:'El distribuidor autorizado Apple en Momentum Pinares. iPhones, MacBooks, iPads, Apple Watch y todos los accesorios del ecosistema Apple con garantía oficial.', logo:'ishop.png', photo:'https://images.unsplash.com/photo-1517420879524-86d64ac2f339?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Sábado',hours:'10:30 am – 8:00 pm'},{days:'Domingo',hours:'10:30 am – 7:00 pm'}], phone:'4001-5257', instagram:'ishop_cr', whatsapp:'50661600274' },
  { slug:'kenana', name:'Kenana', section:'comercios', category:'Comercios · Moda', tagline:'Ropa y accesorios', description:'Moda femenina con tendencias actuales y accesorios complementarios. Kenana ofrece un surtido variado para la mujer que busca estilo, comodidad y buen precio.', logo:'kenana.png', photo:'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Sábados',hours:'10:00 am – 7:00 pm'},{days:'Domingos',hours:'11:00 am – 6:00 pm'}], phone:'2271-6156', instagram:'kenanafashion' },
  { slug:'man-haus', name:'Man Haus', section:'comercios', category:'Comercios · Moda Masculina', tagline:'Tienda de accesorios para hombres', description:'La tienda de accesorios masculinos de Momentum Pinares. Relojes, carteras, cinturones y todo lo que el hombre moderno necesita para completar su estilo.', logo:'man-haus.png', photo:'https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Domingo',hours:'10:00 am – 6:00 pm'},{days:'Lunes a Jueves',hours:'10:00 am – 7:00 pm'},{days:'Viernes y Sábado',hours:'10:00 am – 8:00 pm'}], phone:'6123-9525', instagram:'manhauscr' },
  { slug:'mobil-dress', name:'Mobil Dress', section:'comercios', category:'Comercios · Accesorios Móviles', tagline:'Accesorios de alta tecnología para móviles', description:'Amplia e innovadora gama de accesorios de alta tecnología para dispositivos móviles. Fundas, protectores, cargadores y todo para proteger y personalizar tu teléfono.', logo:'mobil-dress.png', photo:'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Domingos',hours:'10:00 am – 7:00 pm'}], phone:'2272-9429' },
  { slug:'opticas-munkel', name:'Ópticas Münkel', section:'comercios', category:'Comercios · Óptica', tagline:'La principal óptica costarricense', description:'La óptica costarricense de referencia. Exámenes visuales, lentes graduados, lentes de contacto y una amplia selección de armazones para todos los estilos.', logo:'opticas-munkel.png', photo:'https://images.unsplash.com/photo-1508396526590-2e297b276498?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Domingo',hours:'10:00 am – 7:00 pm'}], phone:'2272-9642', instagram:'opticasmunkelcr' },
  { slug:'ottos-corner', name:"Otto's Corner Petshop", section:'comercios', category:'Comercios · Mascotas', tagline:'Porque cada mascota merece lo mejor', description:"En Otto's Corner cada mascota es especial. Alimentos premium, accesorios, juguetes y servicios de grooming para que tu peludito tenga todo lo que merece.", logo:'ottos-corner.png', photo:'https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'10:00 am – 8:00 pm'},{days:'Sábados',hours:'10:30 am – 7:30 pm'},{days:'Domingos',hours:'10:30 am – 7:00 pm'}], phone:'6414-5373', instagram:'ottoscornercr' },
  { slug:'pharmacy-market', name:'Pharmacy Market', section:'comercios', category:'Comercios · Farmacia', tagline:'Farmacia de conveniencia', description:'Farmacia de conveniencia con un amplio surtido de medicamentos, productos de salud y cuidado personal. Atención profesional y servicio de consulta farmacéutica.', logo:'pharmacy-market.png', photo:'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Sábado',hours:'9:00 am – 8:00 pm'},{days:'Domingos',hours:'10:00 am – 5:00 pm'}], phone:'2272-6637', instagram:'pharmacymarketcostarica', whatsapp:'50661519743' },
  { slug:'play-and-dream', name:'Play and Dream', section:'comercios', category:'Comercios · Mobiliario Infantil', tagline:'Fabricantes de Mobiliario Infantil Montessori', description:'Fabricantes de mobiliario infantil Montessori de alta calidad. Camas, escritorios y espacios de juego diseñados para estimular la autonomía y el desarrollo del niño.', logo:'play-and-dream.png', photo:'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Domingo',hours:'10:00 am – 7:00 pm'}], phone:'7076-8373', instagram:'playanddreamcostarica', whatsapp:'50670768373' },
  { slug:'radio-shack', name:'Radio Shack', section:'comercios', category:'Comercios · Tecnología', tagline:'Innovando Tecnología', description:'Todo en tecnología y electrónica en Momentum Pinares. Dispositivos, accesorios, gadgets y soluciones tecnológicas para el hogar y la oficina.', logo:'radio-shack.png', photo:'https://images.unsplash.com/photo-1517420879524-86d64ac2f339?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Domingo',hours:'10:00 am – 7:00 pm'}], phone:'4031-8277', instagram:'radioshackcr' },
  { slug:'refill-to-go', name:'Refill To Go', section:'comercios', category:'Comercios · Sostenibilidad', tagline:'Recarga sostenible', description:'Tienda de recarga sostenible para productos de limpieza y cuidado personal. Reduce tu huella de plástico recargando tus envases favoritos con productos de calidad.', logo:'refill-to-go.png', photo:'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:30 am – 5:30 pm'},{days:'Sábado',hours:'9:00 am – 5:00 pm'}], phone:'8650-1919' },
  { slug:'sleep-gallery', name:'Sleep Gallery', section:'comercios', category:'Comercios · Colchones & Descanso', tagline:'Expertos en Descanso', description:'Los expertos en descanso de Costa Rica. Colchones de alta gama, bases y accesorios para que cada noche sea una experiencia de recuperación y bienestar total.', logo:'sleep-gallery.png', photo:'https://images.unsplash.com/photo-1555041469-149851a2126?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'10:00 am – 7:00 pm'},{days:'Sábados',hours:'10:00 am – 6:00 pm'},{days:'Domingos',hours:'11:00 am – 5:00 pm'}], phone:'2272-3036', instagram:'sleepgallerycr' },
  { slug:'spazio-verde', name:'Spazio Verde', section:'comercios', category:'Comercios · Mercado Natural', tagline:'Mercado Natural y Macrobiótica', description:'Mercado Natural y Macrobiótica para un estilo de vida saludable. Productos orgánicos, naturales y macrobióticos para toda la familia y también para tus mascotas.', logo:'spazio-verde.png', photo:'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Domingo',hours:'9:00 am – 8:00 pm'}], phone:'8576-0777', instagram:'spazio_verde_cr' },
  { slug:'trasciende', name:'Trasciende', section:'comercios', category:'Comercios · Joyería & Accesorios', tagline:'Accesorios y pedrería', description:'Joyería, accesorios y pedrería para quienes buscan piezas con carácter. Diseños únicos que trascienden la moda pasajera y se convierten en parte de tu identidad.', logo:'trasciende.png', photo:'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Jueves',hours:'11:00 am – 7:00 pm'},{days:'Viernes y Sábado',hours:'11:00 am – 8:00 pm'},{days:'Domingos',hours:'11:00 am – 6:00 pm'}], phone:'8925-0043', instagram:'trasciendejoyas' },
  { slug:'trending-store', name:'Trending Store', section:'comercios', category:'Comercios · Moda & Solarium', tagline:'Moda + Solarium', description:'Tienda de moda con el único solarium de Momentum Pinares. Ropa trendy, accesorios de temporada y la posibilidad de conseguir ese bronceado perfecto.', logo:'trending-store.png', photo:'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes',hours:'11:00 am – 7:00 pm'},{days:'Martes a Jueves',hours:'10:00 am – 7:00 pm'},{days:'Viernes y Sábado',hours:'10:00 am – 8:00 pm'},{days:'Domingos',hours:'10:00 am – 6:00 pm'}], phone:'8717-2018', instagram:'trendingstorecr' },
  { slug:'vainilla-beauty', name:'Vainilla Beauty', section:'comercios', category:'Comercios · Salón de Belleza', tagline:'La cadena de salas de belleza más moderna', description:'La mejor y más moderna cadena de salones de belleza de Costa Rica. Cortes, color, tratamientos y servicios de spa capilar para que luzcas y te sientas increíble.', logo:'vainilla-beauty.png', photo:'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Domingos',hours:'9:00 am – 7:00 pm'}], phone:'4070-1036', instagram:'vainillabeautycr' },
  { slug:'vinum-pinares', name:'Vinum Store', section:'comercios', category:'Comercios · Vinos & Licores', tagline:'Los mejores vinos, destilados y accesorios', description:'Todo el mundo del vino, los destilados y los accesorios de cata en un solo lugar. Vinum es la referencia del buen beber en Momentum Pinares.', logo:'vinum.png', photo:'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Miércoles',hours:'10:00 am – 8:00 pm'},{days:'Jueves a Sábado',hours:'10:00 am – 9:00 pm'},{days:'Domingo',hours:'10:00 am – 6:00 pm'}], phone:'2437-7752' },
  { slug:'wkb-honbu-dojo', name:'WKB HONBU DOJO Costa Rica', section:'comercios', category:'Comercios · Artes Marciales', tagline:'Academia de Karate', description:'Academia de karate oficial WKB HONBU DOJO en Costa Rica. Clases para todas las edades y niveles con instructores certificados internacionalmente.', logo:'wkb-honbu-dojo.png', photo:'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Sábado',hours:'8:00 am – 9:00 pm'}], phone:'8636-9276', instagram:'karatewkbcr' },
  { slug:'vitae-pinares', name:'Vitae', section:'comercios', category:'Comercios · Bienestar & Nutrición', tagline:'Bienestar que transforma', description:'Tienda especializada en bienestar y nutrición con una cuidadosa selección de productos naturales, suplementos y artículos de estilo de vida saludable.', logo:'vitae.png', photo:'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Sábado',hours:'9:00 am – 7:00 pm'}], featured:false },
  { slug:'ramstack-pinares', name:'Ramstack', section:'comercios', category:'Comercios · Diseño & Mobiliario', tagline:'Diseño y soluciones para espacios', description:'Especialistas en diseño y soluciones para espacios de trabajo y hogar. Ramstack combina funcionalidad y estética para crear ambientes que inspiran.', logo:'ramstack.png', photo:'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Sábado',hours:'9:00 am – 6:00 pm'}], featured:false },
  { slug:'volvo', name:'Volvo', section:'comercios', category:'Comercios · Automotriz', tagline:'For Life', description:'Showroom oficial de Volvo en Momentum Pinares. Descubre la gama completa de vehículos suecos reconocidos por su seguridad, diseño escandinavo y tecnología de vanguardia.', logo:'volvo.png', photo:'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Sábado',hours:'9:00 am – 6:00 pm'}], featured:false },
  { slug:'la-pegona', name:'La Pegona Smoke Shop', section:'comercios', category:'Comercios · Smoke Shop', tagline:'Smoke Shop', description:'Selección premium de tabacos, cigarros, pipas y accesorios para los aficionados que buscan calidad y variedad en Momentum Pinares.', logo:'la-pegona.png', photo:'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Sábado',hours:'10:00 am – 8:00 pm'}], featured:false },
  { slug:'party-time', name:"It's Party Time", section:'comercios', category:'Comercios · Eventos & Decoración', tagline:'Todo para tu celebración', description:'La tienda de eventos y decoración de Momentum Pinares. Globos, artículos de fiesta, decoraciones temáticas y todo lo necesario para hacer de cada celebración un momento especial.', logo:'party-time.png', photo:'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Sábado',hours:'9:00 am – 7:00 pm'}], featured:false },
  { slug:'hyatt-place', name:'Hyatt Place', section:'comercios', category:'Comercios · Hospitalidad', tagline:'Your perfect place', description:'El Hyatt Place de Momentum Pinares ofrece una experiencia hotelera moderna y confortable. Habitaciones contemporáneas, bar y servicios de primer nivel a minutos de San José.', logo:'hyatt-place.png', photo:'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Domingo',hours:'24 horas'}], featured:false },
]

const pinaresServicios = [
  { slug:'orange-theory', name:'Orangetheory Fitness', section:'servicios', category:'Servicios · Fitness', tagline:'More Life', description:'Entrena con ciencia: el método Orangetheory combina cardio, fuerza y entrenamiento a intervalos monitoreado en tiempo real. Resultados medibles y una comunidad que te impulsa a superar tus límites.', logo:'orange-theory.png', photo:'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'5:30 am – 8:00 pm'},{days:'Sábados y Domingos',hours:'7:00 am – 12:00 md'}], instagram:'orangetheoryfitnesscr', featured:true },
  { slug:'surgical-center', name:'Surgical Center', section:'servicios', category:'Servicios · Centro Quirúrgico', tagline:'Excelencia quirúrgica en Pinares', description:'Centro quirúrgico especializado en cirugías ambulatorias y procedimientos de alta complejidad. Infraestructura de primer nivel y un equipo médico comprometido con tu recuperación.', logo:'surgical-center.png', photo:'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'7:00 am – 5:00 pm'}], featured:false },
  { slug:'larisa-paez', name:'Larisa Páez Wellness Center', section:'servicios', category:'Servicios · Bienestar & Nutrición', tagline:'Wellness Center', description:'Centro de bienestar integral dirigido por Larisa Páez. Nutrición, hábitos saludables y programas personalizados de wellness para mejorar tu calidad de vida desde adentro hacia afuera.', logo:'larisa-paez.png', photo:'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 5:00 pm'}], instagram:'larisapaezwellness', featured:false },
]

const pinaresTorreMedica = [
  { slug:'imagen-test', name:'Imagen Test', section:'torre-medica', category:'Torre Médica · Radiología e Imágenes Médicas', tagline:'Diagnóstico por imagen de alta precisión', description:'Centro especializado en radiología e imágenes médicas. Ultrasonidos, radiografías y estudios de diagnóstico con tecnología avanzada para una detección temprana y precisa.', logo:'torre-medica.png', photo:'https://images.unsplash.com/photo-1516069677018-378515003435?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 8:00 pm'},{days:'Sábados',hours:'8:00 am – 4:00 pm'}], website:'https://directorio.torremedicamomentum.com/es/clinic/imagen-test?ref=sb', featured:true },
  { slug:'labin', name:'Labin', section:'torre-medica', category:'Torre Médica · Laboratorio Clínico', tagline:'Resultados confiables y oportunos', description:'Laboratorio clínico con amplia gama de análisis y exámenes. Resultados rápidos con los más altos estándares de calidad para el diagnóstico médico.', logo:'torre-medica.png', photo:'https://images.unsplash.com/photo-1579154204601-01588f351e67?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 8:00 pm'},{days:'Sábados',hours:'8:00 am – 4:00 pm'}], website:'https://directorio.torremedicamomentum.com/es/clinic/laboratorio-labin?ref=sb', featured:true },
  { slug:'m-surgical-center', name:'M Surgical Center', section:'torre-medica', category:'Torre Médica · Centro Quirúrgico', tagline:'Sala de cirugía y quirófano ambulatorio', description:'Centro quirúrgico ambulatorio de alta complejidad. Sala de operaciones equipada con tecnología de primer nivel para cirugías programadas con los más altos estándares de seguridad.', logo:'torre-medica.png', photo:'https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 8:00 pm'},{days:'Sábados',hours:'8:00 am – 4:00 pm'}], website:'https://directorio.torremedicamomentum.com/es/search/health-service/m-surgical-center?ref=sb', featured:true },
  { slug:'ifisiotx', name:'iFisioTx', section:'torre-medica', category:'Torre Médica · Fisioterapia y Rehabilitación', tagline:'Centro avanzado de fisioterapia y rehabilitación', description:'Centro avanzado de fisioterapia y rehabilitación con técnicas de última generación. Recuperación musculoesquelética, rehabilitación post-operatoria y programas de rendimiento deportivo.', logo:'torre-medica.png', photo:'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 8:00 pm'},{days:'Sábados',hours:'8:00 am – 4:00 pm'}], website:'https://directorio.torremedicamomentum.com/es/clinic/ifisiotx-centro-avanzado-de-fisioterapia-y-rehabilitacion_d8d5c3?ref=sb', featured:false },
  { slug:'larisa-paez-wellness', name:'Larisa Páez Wellness Center', section:'torre-medica', category:'Torre Médica · Nutrición y Bienestar', tagline:'Centro de nutrición y vida saludable', description:'Centro de bienestar integral dirigido por Larisa Páez. Nutrición, hábitos saludables y programas personalizados de wellness para mejorar tu calidad de vida.', logo:'torre-medica.png', photo:'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 8:00 pm'},{days:'Sábados',hours:'8:00 am – 4:00 pm'}], website:'https://directorio.torremedicamomentum.com/es/clinic/centro-de-nutricion-larisa-paez-curridabat?ref=sb', featured:false },
  { slug:'edgar-jimenez-solis', name:'Dr. Edgar Jiménez Solís', section:'torre-medica', category:'Torre Médica · Neurocirugía · Neuro-Oncología · Columna', tagline:'Especialista en neurocirugía y columna vertebral', description:'El Dr. Edgar Jiménez Solís es especialista en Neurocirugía, Neuro-Oncología y Cirugía de Columna Vertebral. Atención de alta complejidad con técnicas mínimamente invasivas.', logo:'torre-medica.png', photo:'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 8:00 pm'}], website:'https://directorio.torremedicamomentum.com/es/doctor/edgar-jimenez-masis', featured:false },
  { slug:'ka-diagnostico-craneofacial', name:'Ka Diagnóstico Craneofacial', section:'torre-medica', category:'Torre Médica · Radiología Craneofacial', tagline:'Diagnóstico radiológico craneofacial especializado', description:'Centro especializado en diagnóstico radiológico craneofacial con tecnología de punta. Tomografías, radiografías panorámicas y estudios de imágenes para odontología y cirugía maxilofacial.', logo:'torre-medica.png', photo:'https://images.unsplash.com/photo-1516069677018-378515003435?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 8:00 pm'},{days:'Sábados',hours:'8:00 am – 4:00 pm'}], website:'https://directorio.torremedicamomentum.com/es/clinic/ka-diagnostico-craneofacial?ref=sb', featured:false },
]

const pinaresOfiplaza = [
  { slug:'oficentro-pinares', name:'Oficentro Momentum Pinares', section:'ofiplaza', category:'Ofiplaza · Oficentro', tagline:'Espacios de oficina premium en Curridabat', description:'El Oficentro de Momentum Pinares ofrece espacios de oficina de alto nivel en una ubicación estratégica en Curridabat. Ideal para empresas y profesionales que buscan imagen, comunidad y conectividad.', logo:'oficentro-pinares.png', photo:'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=500&fit=crop&auto=format&q=80', hours:[{days:'Lunes a Viernes',hours:'8:00 am – 6:00 pm'}], featured:true },
]

// ─── MAIN ─────────────────────────────────────────────────────────────────────

async function main() {
  const allDocs = [
    ...lindoraGastronomia.map(t => doc('lindora', t)),
    ...lindoraComercios.map(t => doc('lindora', t)),
    ...lindoraServicios.map(t => doc('lindora', t)),
    ...lindoraOfiplaza.map(t => doc('lindora', t)),
    ...lindoraMediplaza.map(t => doc('lindora', t)),
    ...escazuGastronomia.map(t => doc('escazu', t)),
    ...escazuServicios.map(t => doc('escazu', t)),
    ...escazuOficentro.map(t => doc('escazu', t)),
    ...escazuCentroMedico.map(t => doc('escazu', t)),
    ...pinaresGastronomia.map(t => doc('pinares', t)),
    ...pinaresComercios.map(t => doc('pinares', t)),
    ...pinaresServicios.map(t => doc('pinares', t)),
    ...pinaresTorreMedica.map(t => doc('pinares', t)),
    ...pinaresOfiplaza.map(t => doc('pinares', t)),
  ]

  console.log(`\n🌱  Seeding ${allDocs.length} tenant documents to Sanity...`)
  console.log(`   Project: ${PROJECT_ID} / ${DATASET}\n`)

  await mutate(allDocs)

  console.log(`\n✅  Done! ${allDocs.length} tenants seeded successfully.`)
  console.log('   Open https://sanity.io/manage to verify in the Studio.\n')
}

main().catch(err => { console.error(err); process.exit(1) })
